### ISSUE TITLE
Error in benq.json

### ISSUE THREAD

**Issue by towolf** [JohnBrodie/pyjector#10]
The command for high altitude mode has a syntax error:

```
        "high_altitude_mode": {
            "command": "Highaltitude",
                "on": "on",
                "off": "off",
                "status": "?"
            }
        },
```

This is missing the line 

```
            "actions": {
```

**Comment by leakim** [comment]
I don't have a benq so I cant verify but do feel free to create a pull request. =)

**Comment by towolf** [comment]
It's a syntax error.

Benq is also missing the `brilliant color`, BS command.
