### ISSUE TITLE
Dmesg not showing port on os x.

### ISSUE THREAD

**Issue by oc-tk** [JohnBrodie/pyjector#2]
Hi, i have issue on 10.11 (El Capitan), i can figure to which port is connected projector (its connected via thunderbolt port - i have thunderbolt -> vga cable). And i have question, will i be able to show with pyjector image or some text on the projector?

**Comment by JohnBrodie** [comment]
Unfortunately I don't have an OSX box to help you out.  You will not be able to show images or text on the projector, only send commands to it like "volume up", "change input to HDMI1", etc.

**Comment by oc-tk** [comment]
do you know any framework/library which will help me to do this? is there any possibility to team viewer?
